alias: 'Switch Control: Outdoor Accent Lights'
description: ''
trigger:
  - platform: time
    at: '15:00'
    id: Start-Time
  - platform: time
    at: '01:00'
    id: End-Time
condition: []
action:
  - delay: 00:{{ (range(1,54)|random|int) }}:00 }}
  - choose:
      - conditions:
          - condition: trigger
            id: Start-Time
        sequence:
          - service: switch.turn_on
            target:
              entity_id:
                - switch.kitchen_window_decoration_outlet_on_off_switch
                - switch.outside_outlet_on_off_switch
    default:
      - service: switch.turn_off
        target:
          entity_id:
            - switch.kitchen_window_decoration_outlet_on_off_switch
            - switch.outside_outlet_on_off_switch
mode: single
