alias: 'Switch Control: Outdoor Accent Lights'
description: ''
trigger:
  - platform: time
    at: input_datetime.time_1500
    id: Start-Time
  - platform: time
    at: input_datetime.time_0100
    id: End-Time
  - platform: event
    event_type: automation_reloaded
    id: Automation-Reloaded
condition: []
action:
  - delay: 00:{{ (range(0,54)|random|int) }}:00
  - choose:
      - conditions:
          - condition: time
            after: input_datetime.time_1500
            before: input_datetime.time_0100
        sequence:
          - service: switch.turn_on
            target:
              entity_id:
                - switch.kitchen_window_decoration_outlet_on_off_switch
                - switch.outside_outlet_on_off_switch
    default:
      - service: switch.turn_off
        target:
          entity_id:
            - switch.kitchen_window_decoration_outlet_on_off_switch
            - switch.outside_outlet_on_off_switch
mode: single
