blueprint:
  name: Inovelli Blue Switch LED Sync to Entity State (zigbee2mqtt)
  description: Calls script.inovelli_blue_led_zigbee2mqtt for state matching with specified entity with on/off states. Requires script has been created. See https://github.com/zanix/home-assistant-config/blob/master/scripts/inovelli_blue/inovelli_blue_led.yaml
  domain: automation
  input:
    source_state_entity:
      name: Source-State Entity
      description: The entity to which switch LED should be set (must report as on/off).
      selector: 
        entity:
          domain:
            - light
    switch_entity: 
      name: Inovelli Dimmer/Switch LED
      description: Inovelli switch device with customizable LED.
      selector: 
        entity:
          domain:
            - light
            - switch
          integration: mqtt
          multiple: false
    on_color:
      name: On Color
      description: Color of the LED bar when `source_state_entity` is `on`.
      default: Green
      selector:
        text:
    on_level:
      name: On Level
      description: Intensity of the LED bar when `source_state_entity` is `on`.
      default: 30
      selector:
        text:
    on_transition_effect:
      name: On Transition Effect
      description: Effect played when `source_state_entity` changes to `on`.
      default: Open/Close
      selector:
        select:
          options:
            - 'Off'
            - 'Clear'
            - 'Solid'
            - 'Aurora'
            - 'Chase'
            - 'Fast Blink'
            - 'Fast Chase'
            - 'Fast Falling'
            - 'Fast Rising'
            - 'Fast Siren'
            - 'Medium Blink'
            - 'Medium Falling'
            - 'Medium Rising'
            - 'Open/Close'
            - 'Pulse'
            - 'Slow Blink'
            - 'Slow Chase'
            - 'Slow Falling'
            - 'Slow Rising'
            - 'Slow Siren'
            - 'Small to Big'
    off_color:
      name: Off Color
      description: Color of the LED bar when `source_state_entity` is `off`.
      default: Blue
      selector:
        text:
    off_level:
      name: Off Level
      description: Intensity of the LED bar when `source_state_entity` is `off`.
      default: 10
      selector:
        text:
    off_transition_effect:
      name: Off Transition Effect
      description: Effect played when `source_state_entity` changes to `off`.
      default: Open/Close
      selector:
        select:
          options:
            - 'Off'
            - 'Clear'
            - 'Solid'
            - 'Aurora'
            - 'Chase'
            - 'Fast Blink'
            - 'Fast Chase'
            - 'Fast Falling'
            - 'Fast Rising'
            - 'Fast Siren'
            - 'Medium Blink'
            - 'Medium Falling'
            - 'Medium Rising'
            - 'Open/Close'
            - 'Pulse'
            - 'Slow Blink'
            - 'Slow Chase'
            - 'Slow Falling'
            - 'Slow Rising'
            - 'Slow Siren'
            - 'Small to Big'
trigger:
  - platform: state
    entity_id: !input 'source_state_entity'
variables:
  source_state_entity: !input 'source_state_entity'
  switch_entity: !input 'switch_entity'
  on_color: !input 'on_color'
  on_level: !input 'on_level'
  on_transition_effect: !input 'on_transition_effect'
  off_color: !input 'off_color'
  off_level: !input 'off_level'
  off_transition_effect: !input 'off_transition_effect'
mode: restart
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input 'source_state_entity'
            state: 'on'
        sequence:
          - service: script.inovelli_blue_led_zigbee2mqtt
            data:
              entity_id:
                - '{{ switch_entity }}'
              led: "0"
              color: '{{ on_color }}'
              level: '{{ on_level }}'
              effect: '{{ on_transition_effect }}'
              duration: 1
          - delay:
              hours: 0
              minutes: 0
              seconds: 0
              milliseconds: 500
          - service: script.inovelli_blue_led_zigbee2mqtt
            data:
              entity_id:
                - '{{ switch_entity }}'
              led: "0"
              color: '{{ on_color }}'
              level: '{{ on_level }}'
              effect: Solid
              duration: Indefinitely
    default:
          - service: script.inovelli_blue_led_zigbee2mqtt
            data:
              entity_id:
                - '{{ switch_entity }}'
              led: "0"
              color: '{{ off_color }}'
              level: '{{ off_level }}'
              effect: '{{ off_transition_effect }}'
              duration: 1
          - delay:
              hours: 0
              minutes: 0
              seconds: 0
              milliseconds: 500
          - service: script.inovelli_blue_led_zigbee2mqtt
            data:
              entity_id:
                - '{{ switch_entity }}'
              led: "0"
              color: '{{ off_color }}'
              level: '{{ off_level }}'
              effect: Solid
              duration: Indefinitely