blueprint:
  name: 'Light Event Handler'
  description: 'Sets a scene stored in Home Assistant helpers when triggered by a supported event.'
  domain: automation
  input:
    light_entity:
      name: Light Entity
      description: The light entity for which scenes will be set.
      selector:
        entity:
          domain: light
    mqtt_topic:
      name: MQTT Topic
      description: The MQTT topic to which 'on' and 'off' messages are published.
      selector:
        text:
    default_scene_helper:
      name: Default Scene Helper
      description: The Home Assistant helper which holds the current default scene name.
      default: input_text.light_scene_helper_default
      selector:
        entity:
          domain: input_text
    default_scene_transition_seconds:
      name: Default Scene Transition Seconds
      description: The amount of time to transition to default scenes.
      default: 0.5
      selector:
        number:
          min: 0
          max: 20
          mode: box
          step: 0.1
          unit_of_measurement: seconds
    media_scene_helper:
      name: Media Scene Helper
      description: The Home Assistant helper which holds the current media-determined scene name.
      default: input_text.light_scene_helper_media_no_client
      selector:
        entity:
          domain: input_text
    media_scene_transition_seconds:
      name: Media Scene Transition Seconds
      description: The amount of time to transition to/from media scenes.
      default: 2
      selector:
        number:
          min: 0
          max: 20
          mode: box
          step: 0.1
          unit_of_measurement: seconds
mode: restart
trigger:
- platform: event
  id: Automation-Reloaded
  event_type: automation_reloaded
- platform: mqtt
  topic: !input mqtt_topic
  payload: 'on'
  id: trigger_on
- platform: mqtt
  topic: !input mqtt_topic
  payload: 'off'
  id: trigger_off
- platform: state
  entity_id: !input default_scene_helper
  id: trigger_default_scene
- platform: state
  entity_id: !input media_scene_helper
  id: trigger_media_scene
variables:
  light_entity: !input light_entity
  default_scene_helper: !input default_scene_helper
  media_scene_helper: !input media_scene_helper
action:
- choose:
  - conditions:
    - condition: or
      conditions:
      - condition: trigger
        id: trigger_on
      - condition: trigger
        id: trigger_default_scene
      - condition: trigger
        id: trigger_media_scene
    sequence:
    - choose:
      - conditions:
        - condition: or
          conditions:
          - condition: and
            conditions:
            - condition: state
              entity_id: !input light_entity
              state: 'off'
            - condition: trigger
              id: trigger_on
          - condition: state
            entity_id: !input light_entity
            state: 'on'
        sequence:
        - choose:
          - conditions:
            - condition: not
              conditions:
              - condition: state
                entity_id: !input media_scene_helper
                state: NO_SCENE_SPECIFIED
            sequence:
            - service: hue.activate_scene
              target:
                entity_id: "{{ (light_entity | replace('light.','scene.')) + '_' + states(media_scene_helper) | lower }}"
              data:
                transition: !input media_scene_transition_seconds
          - conditions:
            - condition: and
              conditions:
              - condition: trigger
                id: trigger_media_scene
              - condition: state
                entity_id: !input media_scene_helper
                state: NO_SCENE_SPECIFIED
            sequence:
              service: hue.activate_scene
              target:
                entity_id: "{{ (light_entity | replace('light.','scene.')) + '_' + states(default_scene_helper) | lower }}"
              data:
                transition: !input media_scene_transition_seconds
          default:
          - service: hue.activate_scene
            target:
              entity_id: "{{ (light_entity | replace('light.','scene.')) + '_' + states(default_scene_helper) | lower }}"
            data:
              transition: !input default_scene_transition_seconds
      default: []
  - conditions:
    - condition: trigger
      id: trigger_off
    sequence:
    - service: light.turn_off
      target:
        entity_id: !input light_entity
      data: {}