blueprint:
  name: 'Light Event Handler'
  description: 'Sets a scene stored in Home Assistant helpers when triggered by a supported event.'
  domain: automation
  input:
    light_entity:
      name: Light Entity
      description: The light entity for which scenes will be set.
      selector:
        entity:
          domain: light
    mqtt_topic:
      name: MQTT Topic
      description: The MQTT topic to which 'on' and 'off' messages are published.
      selector:
        text:
    primary_scene_helper:
      name: Primary Scene Helper
      description: The Home Assistant helper which holds the current primary scene name. This scene will be set when secondary_scene_helper is not set.
      default: input_text.light_scene_helper_default
      selector:
        entity:
          domain: input_text
    primary_scene_transition_seconds:
      name: Primary Scene Transition Seconds
      description: The amount of time to transition to primary scenes.
      default: 0.5
      selector:
        number:
          min: 0
          max: 20
          mode: box
          step: 0.1
          unit_of_measurement: seconds
    secondary_scene_helper:
      name: Secondary Scene Helper
      description: The Home Assistant helper which holds the current secondary-determined scene name. This value is determined externally and can be set for media state, holiday status, etc.
      default: input_text.light_scene_helper_none_selected
      selector:
        entity:
          domain: input_text
    secondary_scene_transition_seconds:
      name: Secondary Scene Transition Seconds
      description: The amount of time to transition to/from secondary scenes.
      default: 2
      selector:
        number:
          min: 0
          max: 20
          mode: box
          step: 0.1
          unit_of_measurement: seconds
mode: restart
trigger:
- platform: event
  id: Automation-Reloaded
  event_type: automation_reloaded
- platform: mqtt
  topic: !input mqtt_topic
  payload: 'on'
  id: trigger_on
- platform: mqtt
  topic: !input mqtt_topic
  payload: 'off'
  id: trigger_off
- platform: state
  entity_id: !input primary_scene_helper
  id: trigger_primary_scene
- platform: state
  entity_id: !input secondary_scene_helper
  id: trigger_secondary_scene
- platform: state
  entity_id: !input light_entity
  from: 'off'
  to: 'on'
variables:
  light_entity: !input light_entity
  primary_scene_helper: !input primary_scene_helper
  secondary_scene_helper: !input secondary_scene_helper
  scene_prefix: "{{ (light_entity | replace('light.','scene.')) + '_' }}"
action:
- choose:
  - conditions:
    - condition: or
      conditions:
      - condition: trigger
        id: trigger_on
      - condition: trigger
        id: trigger_primary_scene
      - condition: trigger
        id: trigger_secondary_scene
    sequence:
    - choose:
      # light is on or was triggered to turn on
      - conditions:
        - condition: or
          conditions:
          - condition: and
            conditions:
            - condition: state
              entity_id: !input light_entity
              state: 'off'
            - condition: trigger
              id: trigger_on
          - condition: state
            entity_id: !input light_entity
            state: 'on'
        sequence:
        - choose:
          # if secondary helper has a scene specified, use that one
          - conditions:
            - condition: not
              conditions:
              - condition: state
                entity_id: !input secondary_scene_helper
                state: NO_SCENE_SPECIFIED
            sequence:
            - service: hue.activate_scene
              target:
                entity_id: "{{ scene_prefix + states(secondary_scene_helper) | lower }}"
              data:
                transition: !input secondary_scene_transition_seconds
          # if secondary helper has no scene specified but triggered the automation, use primary with secondary transition time
          - conditions:
            - condition: and
              conditions:
              - condition: trigger
                id: trigger_secondary_scene
              - condition: state
                entity_id: !input secondary_scene_helper
                state: NO_SCENE_SPECIFIED
            sequence:
              service: hue.activate_scene
              target:
                entity_id: "{{ scene_prefix + states(primary_scene_helper) | lower }}"
              data:
                transition: !input secondary_scene_transition_seconds
          # secondary helper has no scene specified and did not trigger the automation
          default:
          - service: hue.activate_scene
            target:
              entity_id: "{{ scene_prefix + states(primary_scene_helper) | lower }}"
            data:
              transition: !input primary_scene_transition_seconds
      default: []
  # turn light off
  - conditions:
    - condition: trigger
      id: trigger_off
    sequence:
    - service: light.turn_off
      target:
        entity_id: !input light_entity
      data: {}
