blueprint:
  name: Light-Switch-AL Controller
  description: |
    Set light configuration based on switch and adaptive lighting states. The following configuration should be applied:
      * Light group
          - All light devices are added to a light group
          - Switch is added to the same light group
          - Zigbee switch has a 'Level' binding to the light goup. If not using Zigbee, this is untested.
      * Switch
          - Dimmer mode: true
      * Adaptive Lighting
          - Configured for the light group
          - `take_over_control` is disabled
  domain: automation
  input:
    light:
      name: Light Group
      description: The light group.
      selector:
        entity:
          domain: light
    switch_sensor:
      name: Switch Action Sensor
      description: The switch sensor that reflects action state.
      selector:
        entity:
          domain: sensor
          multiple: true
mode: single
trigger:
  - platform: state
    entity_id: !input light
    to: "off"
    id: light_turned_off
  - platform: state
    entity_id: !input light
    to: "on"
    id: light_turned_on
  - platform: state
    entity_id: !input switch_sensor
    to: down_held
    id: switch_down_held
  - platform: state
    entity_id: !input switch_sensor
    to: up_held
    id: switch_up_held
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id:
              - light_turned_on
        sequence:
          - delay:
              hours: 0
              minutes: 0
              seconds: 0
              milliseconds: 500
            enabled: false
          - service: adaptive_lighting.set_manual_control
            data:
              manual_control: false
              lights:
                - !input light
          - service: adaptive_lighting.apply
            data:
              lights:
                - !input light
      - conditions:
          - condition: trigger
            id:
              - switch_down_held
              - switch_up_held
        sequence:
          - service: adaptive_lighting.set_manual_control
            data:
              manual_control: true
              lights:
                - !input light
      - conditions:
          - condition: trigger
            id:
              - light_turned_off
        sequence:
          - service: adaptive_lighting.set_manual_control
            data:
              manual_control: false
              lights:
                - !input light
