blueprint:
  name: Media Scene Selector
  description: Monitors a playback device and sets scene names to a Home Assistant helper.
  domain: automation
  input:
    media_entity:
      name: Media Player
      description: The media player entity that will be monitored.
      selector:
        entity:
          domain: media_player
    media_scene_helper:
      name: Media Scene Helper
      description: The Home Assistant helper which holds the current playback-determined scene name.
      default: input_text.light_scene_plex_no_client
      selector:
        entity:
          domain: input_text
    phase_helper:
      name: Phase Helper
      description: The Home Assistant helper which holds the current phase name.
      default: !input phase_helper
      selector:
        entity:
          domain: input_select   
    morning_playing_movie_scene:
      name: Morning-Playing-Movie Scene
      description: Scene for phase:morning, playback:playing, type:movie.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
    morning_playing_episode_scene:
      name: Morning-Playing-Episode Scene
      description: Scene for phase:morning, playback:playing, type:episode.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
    morning_paused_movie_scene:
      name: Morning-Paused-Movie Scene
      description: Scene for phase:morning, playback:paused, type:movie.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
    morning_paused_episode_scene:
      name: Morning-Paused-Episode Scene
      description: Scene for phase:morning, playback:paused, type:episode.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
    day_playing_movie_scene:
      name: Day-Playing-Movie Scene
      description: Scene for phase:day, playback:playing, type:movie.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
    day_playing_episode_scene:
      name: Day-Playing-Episode Scene
      description: Scene for phase:day, playback:playing, type:episode.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
    day_paused_movie_scene:
      name: Day-Paused-Movie Scene
      description: Scene for phase:day, playback:paused, type:movie.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
    day_paused_episode_scene:
      name: Day-Paused-Episode Scene
      description: Scene for phase:day, playback:paused, type:episode.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
    evening_playing_movie_scene:
      name: Evening-Playing-Movie Scene
      description: Scene for phase:evening, playback:playing, type:movie.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
    evening_playing_episode_scene:
      name: Evening-Playing-Episode Scene
      description: Scene for phase:evening, playback:playing, type:episode.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
    evening_paused_movie_scene:
      name: Evening-Paused-Movie Scene
      description: Scene for phase:evening, playback:paused, type:movie.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
    evening_paused_episode_scene:
      name: Evening-Paused-Episode Scene
      description: Scene for phase:evening, playback:paused, type:episode.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
    night_playing_movie_scene:
      name: Night-Playing-Movie Scene
      description: Scene for phase:night, playback:playing, type:movie.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
    night_playing_episode_scene:
      name: Night-Playing-Episode Scene
      description: Scene for phase:night, playback:playing, type:episode.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
    night_paused_movie_scene:
      name: Night-Paused-Movie Scene
      description: Scene for phase:night, playback:paused, type:movie.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
    night_paused_episode_scene:
      name: Night-Paused-Episode Scene
      description: Scene for phase:night, playback:paused, type:episode.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
mode: restart
trigger:
- platform: state
  entity_id: !input media_scene_helper
  id: trigger_media_state
- platform: state
  entity_id: !input phase_helper
  id: trigger_phase_state
variables:
  media_entity: !input media_entity
  playback_state: "{{ states(media_entity) }}"
  playback_type: "{{ state_attr(media_entity,'media_content_type') | default('default',true) }}"
  phase_helper: !input phase_helper
  current_phase: "{{ states(phase_helper) }}"
  scene_variable: "{{ current_phase + '_' + playback_state + '_' + playback_type }}"
  current_prefix: "{{ (light_entity | replace('light.','scene.')) + '_' }}"
condition:
  - or:
    - and:
      - condition: trigger
        id: trigger_phase_state
      - not:
        - condition: state
          entity_id: !input media_entity
          state: stopped
        - condition: state
          entity_id: !input media_entity
          state: unavailable 
    - condition: trigger
      id: trigger_media_state
action:
- choose:
  - conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: !input media_entity
        state: playing
      - condition: state
        entity_id: !input media_entity
        attribute: media_content_type
        state: movie
      - condition: state
        entity_id: !input phase_helper
        state: Morning
    sequence:
    - service: input_text.set_value
      data:
        value: Movie
      target:
        entity_id: !input media_scene_helper
  - conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: !input media_entity
        state: playing
      - condition: state
        entity_id: !input media_entity
        attribute: media_content_type
        state: movie
      - condition: state
        entity_id: !input phase_helper
        state: Day
    sequence:
    - service: input_text.set_value
      data:
        value: Movie
      target:
        entity_id: !input media_scene_helper
  - conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: !input media_entity
        state: playing
      - condition: state
        entity_id: !input media_entity
        attribute: media_content_type
        state: movie
      - condition: state
        entity_id: !input phase_helper
        state: Evening
    sequence:
    - service: input_text.set_value
      data:
        value: Movie
      target:
        entity_id: !input media_scene_helper
  - conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: !input media_entity
        state: playing
      - condition: state
        entity_id: !input media_entity
        attribute: media_content_type
        state: movie
      - condition: state
        entity_id: !input phase_helper
        state: Night
    sequence:
    - service: input_text.set_value
      data:
        value: Movie
      target:
        entity_id: !input media_scene_helper
  - conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: !input media_entity
        state: playing
      - condition: state
        entity_id: !input media_entity
        attribute: media_content_type
        state: episode
      - condition: state
        entity_id: !input phase_helper
        state: Morning
    sequence:
    - service: input_text.set_value
      data:
        value: Episode
      target:
        entity_id: !input media_scene_helper
  - conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: !input media_entity
        state: playing
      - condition: state
        entity_id: !input media_entity
        attribute: media_content_type
        state: episode
      - condition: state
        entity_id: !input phase_helper
        state: Day
    sequence:
    - service: input_text.set_value
      data:
        value: Episode
      target:
        entity_id: !input media_scene_helper
  - conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: !input media_entity
        state: playing
      - condition: state
        entity_id: !input media_entity
        attribute: media_content_type
        state: episode
      - condition: state
        entity_id: !input phase_helper
        state: Evening
    sequence:
    - service: input_text.set_value
      data:
        value: NO_SCENE_SPECIFIED
      target:
        entity_id: !input media_scene_helper
  - conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: !input media_entity
        state: playing
      - condition: state
        entity_id: !input media_entity
        attribute: media_content_type
        state: episode
      - condition: state
        entity_id: !input phase_helper
        state: Night
    sequence:
    - service: input_text.set_value
      data:
        value: NO_SCENE_SPECIFIED
      target:
        entity_id: !input media_scene_helper
  - conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: !input media_entity
        state: paused
      - condition: state
        entity_id: !input media_entity
        attribute: media_content_type
        state: movie
      - condition: state
        entity_id: !input phase_helper
        state: Morning
    sequence:
    - service: input_text.set_value
      data:
        value: NO_SCENE_SPECIFIED
      target:
        entity_id: !input media_scene_helper
  - conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: !input media_entity
        state: paused
      - condition: state
        entity_id: !input media_entity
        attribute: media_content_type
        state: movie
      - condition: state
        entity_id: !input phase_helper
        state: Day
    sequence:
    - service: input_text.set_value
      data:
        value: Dimmed
      target:
        entity_id: !input media_scene_helper
  - conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: !input media_entity
        state: paused
      - condition: state
        entity_id: !input media_entity
        attribute: media_content_type
        state: movie
      - condition: state
        entity_id: !input phase_helper
        state: Evening
    sequence:
    - service: input_text.set_value
      data:
        value: NO_SCENE_SPECIFIED
      target:
        entity_id: !input media_scene_helper
  - conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: !input media_entity
        state: paused
      - condition: state
        entity_id: !input media_entity
        attribute: media_content_type
        state: movie
      - condition: state
        entity_id: !input phase_helper
        state: Night
    sequence:
    - service: input_text.set_value
      data:
        value: NO_SCENE_SPECIFIED
      target:
        entity_id: !input media_scene_helper
  - conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: !input media_entity
        state: paused
      - condition: state
        entity_id: !input media_entity
        attribute: media_content_type
        state: episode
      - condition: state
        entity_id: !input phase_helper
        state: Morning
    sequence:
    - service: input_text.set_value
      data:
        value: NO_SCENE_SPECIFIED
      target:
        entity_id: !input media_scene_helper
  - conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: !input media_entity
        state: paused
      - condition: state
        entity_id: !input media_entity
        attribute: media_content_type
        state: episode
      - condition: state
        entity_id: !input phase_helper
        state: Day
    sequence:
    - service: input_text.set_value
      data:
        value: NO_SCENE_SPECIFIED
      target:
        entity_id: !input media_scene_helper
  - conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: !input media_entity
        state: paused
      - condition: state
        entity_id: !input media_entity
        attribute: media_content_type
        state: episode
      - condition: state
        entity_id: !input phase_helper
        state: Evening
    sequence:
    - service: input_text.set_value
      data:
        value: NO_SCENE_SPECIFIED
      target:
        entity_id: !input media_scene_helper
  - conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: !input media_entity
        state: paused
      - condition: state
        entity_id: !input media_entity
        attribute: media_content_type
        state: episode
      - condition: state
        entity_id: !input phase_helper
        state: Night
    sequence:
    - service: input_text.set_value
      data:
        value: NO_SCENE_SPECIFIED
      target:
        entity_id: !input media_scene_helper
  default:
  - service: input_text.set_value
    data:
      value: NO_SCENE_SPECIFIED
    target:
      entity_id: !input media_scene_helper

