blueprint:
  name: Media Scene Selector
  description: Monitors a playback device and sets scene names to a Home Assistant helper.
  domain: automation
  input:
    media_entity:
      name: Media Player
      description: The media player entity that will be monitored.
      selector:
        entity:
          domain: media_player
    scene_helper:
      name: Scene Helper
      description: The Home Assistant helper which holds the current playback-determined scene name.
      selector:
        entity:
          domain: input_text
    phase_helper:
      name: Phase Helper
      description: The Home Assistant helper which holds the current phase name.
      default: !input phase_helper
      selector:
        entity:
          domain: input_select
    no_exec_phases:
      name: No Execution Phases
      description: The comma separated phases in which the automation should be blocked from executing.
      default: ""
      selector:
        text:
    mode_helper:
      name: Mode Entity
      description: The helper which hold current mode. This helper's state will be compared when do_not_publish_modes is set.
      default: {}
      selector:
        entity:
          domain: input_select 
    no_exec_modes:
      name: No Execution Modes
      description: The comma separated modes in which the automation should be blocked from executing.
      default: ""
      selector:
        text:
    morning_playing_movie_scene:
      name: Morning-Playing-Movie Scene
      description: Scene for phase:morning, playback:playing, type:movie.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
    morning_playing_tvshow_scene:
      name: Morning-Playing-TVShow Scene
      description: Scene for phase:morning, playback:playing, type:tvshow.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
    morning_playing_default_scene:
      name: Morning-Playing-Default Scene
      description: Scene for phase:morning, playback:playing when media type cannot be determined.
      default: NO_SCENE_SPECIFIED
      selector:
        text:    
    morning_paused_movie_scene:
      name: Morning-Paused-Movie Scene
      description: Scene for phase:morning, playback:paused, type:movie.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
    morning_paused_tvshow_scene:
      name: Morning-Paused-TVShow Scene
      description: Scene for phase:morning, playback:paused, type:tvshow.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
    morning_paused_default_scene:
      name: Morning-Paused-Default Scene
      description: Scene for phase:morning, playback:paused when media type cannot be determined.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
    day_playing_movie_scene:
      name: Day-Playing-Movie Scene
      description: Scene for phase:day, playback:playing, type:movie.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
    day_playing_tvshow_scene:
      name: Day-Playing-TVShow Scene
      description: Scene for phase:day, playback:playing, type:tvshow.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
    day_playing_default_scene:
      name: Day-Playing-Default Scene
      description: Scene for phase:day, playback:playing when media type cannot be determined.
      default: NO_SCENE_SPECIFIED
      selector:
        text:    
    day_paused_movie_scene:
      name: Day-Paused-Movie Scene
      description: Scene for phase:day, playback:paused, type:movie.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
    day_paused_tvshow_scene:
      name: Day-Paused-TVShow Scene
      description: Scene for phase:day, playback:paused, type:tvshow.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
    day_paused_default_scene:
      name: Day-Paused-Default Scene
      description: Scene for phase:day, playback:paused when media type cannot be determined.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
    evening_playing_movie_scene:
      name: Evening-Playing-Movie Scene
      description: Scene for phase:evening, playback:playing, type:movie.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
    evening_playing_tvshow_scene:
      name: Evening-Playing-TVShow Scene
      description: Scene for phase:evening, playback:playing, type:tvshow.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
    evening_playing_default_scene:
      name: Evening-Playing-Default Scene
      description: Scene for phase:evening, playback:playing when media type cannot be determined.
      default: NO_SCENE_SPECIFIED
      selector:
        text:  
    evening_paused_movie_scene:
      name: Evening-Paused-Movie Scene
      description: Scene for phase:evening, playback:paused, type:movie.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
    evening_paused_tvshow_scene:
      name: Evening-Paused-TVShow Scene
      description: Scene for phase:evening, playback:paused, type:tvshow.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
    evening_paused_default_scene:
      name: Evening-Paused-Default Scene
      description: Scene for phase:evening, playback:paused when media type cannot be determined.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
    night_playing_movie_scene:
      name: Night-Playing-Movie Scene
      description: Scene for phase:night, playback:playing, type:movie.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
    night_playing_tvshow_scene:
      name: Night-Playing-TVShow Scene
      description: Scene for phase:night, playback:playing, type:tvshow.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
    night_playing_default_scene:
      name: Night-Playing-Default Scene
      description: Scene for phase:night, playback:playing when media type cannot be determined.
      default: NO_SCENE_SPECIFIED
      selector:
        text:  
    night_paused_movie_scene:
      name: Night-Paused-Movie Scene
      description: Scene for phase:night, playback:paused, type:movie.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
    night_paused_tvshow_scene:
      name: Night-Paused-TVShow Scene
      description: Scene for phase:night, playback:paused, type:tvshow.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
    night_paused_default_scene:
      name: Night-Paused-Default Scene
      description: Scene for phase:night, playback:paused when media type cannot be determined.
      default: NO_SCENE_SPECIFIED
      selector:
        text:
mode: restart
trigger:
- platform: state
  entity_id: !input media_entity
  id: trigger_media_state
- platform: state
  entity_id: !input phase_helper
  id: trigger_phase_state
- platform: state
  entity_id: !input mode_helper
  id: trigger_mode_state
variables:
  media_entity: !input media_entity
  media_state: "{{ states(media_entity) }}"
  media_type: "{{ state_attr(media_entity, 'media_content_type') | default('default',true) }}"
  scene_helper: !input scene_helper
  phase_helper: !input phase_helper
  no_exec_phases: !input no_exec_phases
  no_exec_phases_list: "{{ (no_exec_phases | lower | replace(', ',',') | replace(' ,',',')).split(',') }}"
  mode_helper: !input mode_helper
  no_exec_modes: !input no_exec_modes
  no_exec_modes_list: "{{ (no_exec_modes | lower | replace(', ',',') | replace(' ,',',')).split(',') }}"
  current_phase: "{{ states(phase_helper) | lower }}"
  morning_playing_movie_scene: !input morning_playing_movie_scene
  morning_playing_tvshow_scene: !input morning_playing_tvshow_scene
  morning_playing_default_scene: !input morning_playing_default_scene
  morning_paused_movie_scene: !input morning_paused_movie_scene
  morning_paused_tvshow_scene: !input morning_paused_tvshow_scene
  morning_paused_default_scene: !input morning_paused_default_scene
  day_playing_movie_scene: !input day_playing_movie_scene
  day_playing_tvshow_scene: !input day_playing_tvshow_scene
  day_playing_default_scene: !input day_playing_default_scene
  day_paused_movie_scene: !input day_paused_movie_scene
  day_paused_tvshow_scene: !input day_paused_tvshow_scene
  day_paused_default_scene: !input day_paused_default_scene
  evening_playing_movie_scene: !input evening_playing_movie_scene
  evening_playing_tvshow_scene: !input evening_playing_tvshow_scene
  evening_playing_default_scene: !input evening_playing_default_scene
  evening_paused_movie_scene: !input evening_paused_movie_scene
  evening_paused_tvshow_scene: !input evening_paused_tvshow_scene
  evening_paused_default_scene: !input evening_paused_default_scene
  night_playing_movie_scene: !input night_playing_movie_scene
  night_playing_tvshow_scene: !input night_playing_tvshow_scene
  night_playing_default_scene: !input night_playing_default_scene
  night_paused_movie_scene: !input night_paused_movie_scene
  night_paused_tvshow_scene: !input night_paused_tvshow_scene
  night_paused_default_scene: !input night_paused_default_scene
  scene_pattern: "{{ current_phase + '-' + media_state + '-' + media_type }}"
  scene_list: >
    {{ [
      {'name':'morning-playing-movie','scene':morning_playing_movie_scene},
      {'name':'morning-playing-tvshow','scene':morning_playing_tvshow_scene},
      {'name':'morning-playing-default','scene':morning_playing_default_scene},
      {'name':'morning-paused-movie','scene':morning_paused_movie_scene},
      {'name':'morning-paused-tvshow','scene':morning_paused_tvshow_scene},
      {'name':'morning-paused-default','scene':morning_paused_default_scene},
      {'name':'day-playing-movie','scene':day_playing_movie_scene},
      {'name':'day-playing-tvshow','scene':day_playing_tvshow_scene},
      {'name':'day-playing-default','scene':day_playing_default_scene},
      {'name':'day-paused-movie','scene':day_paused_movie_scene},
      {'name':'day-paused-tvshow','scene':day_paused_tvshow_scene},
      {'name':'day-paused-default','scene':day_paused_default_scene},
      {'name':'evening-playing-movie','scene':evening_playing_movie_scene},
      {'name':'evening-playing-tvshow','scene':evening_playing_tvshow_scene},
      {'name':'evening-playing-default','scene':evening_playing_default_scene},
      {'name':'evening-paused-movie','scene':evening_paused_movie_scene},
      {'name':'evening-paused-tvshow','scene':evening_paused_tvshow_scene},
      {'name':'evening-paused-default','scene':evening_paused_default_scene},
      {'name':'night-playing-movie','scene':night_playing_movie_scene},
      {'name':'night-playing-tvshow','scene':night_playing_tvshow_scene},
      {'name':'night-playing-default','scene':night_playing_default_scene},
      {'name':'night-paused-movie','scene':night_paused_movie_scene},
      {'name':'night-paused-tvshow','scene':night_paused_tvshow_scene},
      {'name':'night-paused-default','scene':night_paused_default_scene}
    ] }}
  scene: >
    {%- for i in scene_list -%}
      {%- if (i['name'] == scene_pattern) -%}
        {{ i['scene'] }}
      {%- endif -%}
    {%- endfor %}
condition:
- condition: and
  conditions:
  # (trigger_phase_state changed AND media is playing/paused) OR trigger_media_state
  - condition: or
    conditions:
    - condition: and
      conditions:
      - condition: trigger
        id: trigger_phase_state
      - condition: template
        value_template: "{{ media_state == 'playing' or media_state == 'paused' }}"
    - condition: and
      conditions:
      - condition: trigger
        id: trigger_mode_state
      - condition: template
        value_template: "{{ media_state == 'playing' or media_state == 'paused' }}"
    - condition: trigger
      id: trigger_media_state
  # current phase is _not_ in no_exec_phases_list
  - condition: not
    conditions:
    - condition: template
      value_template: "{{ current_phase in no_exec_phases_list }}"
  # mode_helper is not set OR make sure current mode is not in no_exec_modes_list
  - condition: or
    conditions:
    - condition: template
      value_template: "{{ mode_helper == none }}"
    - condition: not
      conditions:
      - condition: template
        value_template: "{{ states(mode_helper) in no_exec_modes_list }}"
action:
- choose:
  - conditions:
    - condition: template
      value_template: "{{ scene != '' and scene != None }}"
    sequence:
    - service: input_text.set_value
      data:
        value: "{{ scene }}"
      target:
        entity_id: "{{ scene_helper }}"
  default:
  - service: input_text.set_value
    data:
      value: 'NO_SCENE_SPECIFIED'
    target:
      entity_id: "{{ scene_helper }}"
