blueprint:
  name: Set Inovelli Switch LED to Entity State
  description: Calls script.set_inovelli_dimmer_switch_led for state matching with specified entity with on/off states.
  domain: automation
  input:
    entity_with_on_off:
      name: Source Entity
      description: The entity to which switch LED should be set (must report as on/off).
      selector: 
        entity: null
    switch_led: 
      name: Inovelli Dimmer/Switch LED
      description: Inovelli switch device with customizable LED.
      selector: 
        entity: 
          domain: sensor
          integration: zwave_js
    switch_model: 
      name: Model of Inovelli device
      selector: 
        select: 
          options: 
            - switch
            - dimmer
            - combo_light
trigger:
  - platform: state
    entity_id: !input 'entity_with_on_off'
variables:
  switch_led: !input 'switch_led'
  switch_model: !input 'switch_model'
mode: restart
action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input 'entity_with_on_off'
            state: 'on'
        sequence:
          - service: script.set_inovelli_dimmer_switch_led
            data:
              entity_id: '{{ switch_led }}'
              model: '{{ switch_model }}'
              color: Green
              duration: Indefinitely
              effect: Solid
    default:
      - service: script.set_inovelli_dimmer_switch_led
        data:
          entity_id: '{{ switch_led }}'
          model: '{{ switch_model }}'
          effect: 'Off'