# This blueprint will create an automation to set lights via Phase change and Plex playback status.
blueprint:
  name: Update Lights on Home Phase & Entity State Changes
  description: Automation calls Hue service to set scenes based on home_phase and entity state changes.
  domain: automation
  input:
    light_entity:
      description: Hue light or group.
      selector:
        entity:
          domain: light
    phase_entity:
      description: Entity used for tracking home phases.
      selector:
        entity:
          domain: input_select
    hue_defaults_script:
      name: Hue Default Scene Script
      description: Script used to set Hue lights to default state based on home_phase.
      default: script.set_hue_light_default_scene_plex_optional
      selector:
        entity:
          domain: script
    hue_scene_day:
      description: Default Hue scene for day time.
      default: Concentrate
      selector:
        text: null
    hue_scene_night:
      description: Default Hue scene for night time.
      default: Relax
      selector:
        text: null
variables:
      light_entity: !input 'light_entity'
      hue_scene_day: !input 'hue_scene_day'
      hue_scene_night: !input 'hue_scene_night'
      hue_defaults_script: !input 'hue_defaults_script'
trigger:
  - platform: state
    entity_id: !input phase_entity
  - platform: state
    entity_id: !input light_entity
    from: 'off'
    to: 'on'
mode: parallel
max: 5
condition:
  condition: state
  entity_id: !input light_entity
  state: 'on'
action:
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - condition: state
    entity_id: '{{ light_entity }}'
    state: 'on'
  - service: '{{ hue_defaults_script }}'
    data:
      light_entity: '{{ light_entity }}'
      hue_scene_day: '{{ hue_scene_day }}'
      hue_scene_night: '{{ hue_scene_night }}'