# This blueprint will create an automation to set lights via Plex playback status.
# Version 1.0
# Improvement_to_do:
# - be able to specify which scenes when building automation
# - will need ability to return to "default" scene at time of playback stop
# INCOMPLETE
blueprint:
  name: Set Lights on Home Phase, Media Device, etc.
  description: Automation calls Hue service to set scenes based on media player playback status.
  domain: automation
  input:
    light_entity:
      description: Hue light or group.
      selector:
        entity:
          domain: light
    hue_scene_day:
      description: Default Hue scene for day time.
      default: Concentrate
      selector:
        text: null
    hue_scene_night:
      description: Default Hue scene for night time.
      default: Relax
      selector:
        text: null
    media_entity:
      description: Media player entity that will trigger execution.
      selector:
        entity:
          domain: media_player
    hue_scene_day_movie_playing:
      description: Hue scene for movie playing in day time.
      default: Movie
      selector:
        text: null
    hue_scene_day_movie_paused:
      description: Hue scene for movie paused in day time.
      default: Concentrate
      selector:
        text: null
    hue_scene_day_tvshow_playing:
      description: Hue scene for episode playing in day time.
      default: Concentrate
      selector:
        text: null
    hue_scene_day_tvshow_paused:
      description: Hue scene for episode paused day time.
      default: Concentrate
      selector:
        text: null
    hue_scene_night_movie_playing:
      description: Hue scene for movie playing in night time.
      default: Relax
      selector:
        text: null
    hue_scene_night_movie_paused:
      description: Hue scene for movie paused night time.
      default: Relax
      selector:
        text: null
    hue_scene_night_tvshow_playing:
      description: Hue scene for episode playing in night time.
      default: Relax
      selector:
        text: null
    hue_scene_night_tvshow_paused:
      description: Hue scene for episode paused in night time.
      default: Relax
      selector:
        text: null
    phase_entity:
      description: Entity used for tracking home phases.
      selector:
        entity:
          domain: input_select
    illuminance_entity:
      description: "NOT YET SUPPORTED: Sensor used to determine illuminance."
      selector:
        entity:
          domain: sensor
    illuminance_threshold:
      description: "NOT YET SUPPORTED: Illunimance value at which lights will turn of/off automatically."
      selector:
        number:
          min: 0
          max: 30000
          step: 100
          unit_of_measurement: lux
          mode: slider
    hue_defaults_script:
      name: Hue Default Scene Script
      description: Script used to set Hue lights to default state based on home_phase.
      selector:
        entity:
          domain: script
trigger:
  - platform: state
    entity_id: !input phase_entity
  - platform: state
    entity_id: !input media_entity
mode: parallel
max: 5
conditions:
  - condition: state
    entity_id: !input light_entity
    state: 'on'
action:
  sequence:
    - service: {{ hue_defaults_script }}
      data:
        light_entity: {{ light_entity }}
        hue_scene_day: {{ hue_scene_day }}
        hue_scene_night: {{ hue_scene_night }}

  # - choose:
  #     - conditions:
  #         - condition: state
  #           entity_id: !input 'entity_with_on_off'
  #           state: 'on'
  #       sequence:
  #         - service: script.set_inovelli_dimmer_switch_led
  #           data:
  #             entity_id: '{{ switch_led }}'
  #             model: '{{ switch_model }}'
  #             color: Green
  #             duration: Indefinitely
  #             effect: Solid
  #   default:
  #     - service: script.set_inovelli_dimmer_switch_led
  #       data:
  #         entity_id: '{{ switch_led }}'
  #         model: '{{ switch_model }}'
  #         effect: 'Off'